name: myriad
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  google_sign_in: ^6.2.2
  shared_preferences: ^2.3.5
  dash_chat_2: ^0.0.20
  flutter_gemini: ^3.0.0
  flutter_svg: ^2.0.17
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/login_asset.png
    - assets/google_icon.png