name: myriad
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  google_sign_in: ^6.2.2
  shared_preferences: ^2.3.5
  dash_chat_2: ^0.0.20
  flutter_gemini: ^3.0.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.6
  url_launcher: ^6.0.20
  audioplayers: ^6.1.0
  flutter_tts: ^3.4.0
  speech_to_text: ^7.0.0
  camera: ^0.11.1
  image: ^4.5.2
  vibration: ^3.1.2
  sensors_plus: ^6.1.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.4.4
  go_router: ^14.8.0
  map_launcher: ^3.5.0
  syncfusion_flutter_charts: ^28.2.5+1
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_light.svg
    - assets/logo_dark.svg
    - assets/login_asset.png
    - assets/community_asset.png
    - assets/google_icon.png
    - assets/scream.mp3
    - assets/angelic.mp3
    - assets/kalimba.mp3
    - assets/bells.mp3
    - assets/bowls.mp3
    - assets/rain.mp3
    - assets/vocal.mp3
    - assets/chirping.mp3
    - assets/Frame_Meditate.png
    - assets/Frame_Sleep.png
    - assets/Frame_Breathe.png
    - assets/Frame_Affirmate.png
    - assets/Serenify_Round_Button.png